import os
import json
import requests
from datetime import datetime
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from google import genai
from google.genai import types

# Initialize the SDK client (Make sure GEMINI_API_KEY is in your environment variables)
load_dotenv()
client = genai.Client()
MODEL_ID = 'gemini-2.5-flash'

# =====================================================================
# 1. PYDANTIC SCHEMA FOR STRUCTURED OUTPUT
# =====================================================================
class ChatAnalysis(BaseModel):
    action_required: str = Field(
        description="Must be either 'explain' if there are academic misconceptions, or 'lock_in' if they are procrastinating."
    )
    summary_message: str = Field(
        description="A short, punchy message to send to Discord. Either roasting them to lock in, or offering an explanation for their gaps."
    )
    topics_to_explain: list[str] = Field(
        description="A list of specific concepts they are getting wrong. Leave empty if action_required is 'lock_in'."
    )
    student_level: str = Field(
        description="Your assessment of their academic level based on the chat (e.g., 'Middle School', 'High School', 'Undergrad', 'Postgrad')."
    )
    subject_area: str = Field(
        description="The general subject they are discussing (e.g., 'Biology', 'Literature', 'Calculus', 'History'). Leave empty if off-task."
    )


class QuizQuestion(BaseModel):
    question: str = Field(description="The quiz question text.")
    options: list[str] = Field(description="Exactly 4 answer options labelled A-D. Each item is the full option text like 'A) Answer text'.")
    correct_answer: str = Field(description="The letter of the correct answer: A, B, C, or D.")
    explanation: str = Field(description="A short explanation of why the correct answer is right and common misconceptions.")


class QuizOutput(BaseModel):
    quiz_title: str = Field(description="A short, catchy title for the quiz.")
    questions: list[QuizQuestion] = Field(description="A list of 5 multiple-choice quiz questions.")
# =====================================================================
# 2. THE SYSTEM PROMPTS
# =====================================================================
ANALYZER_PROMPT = """
You are a highly intelligent, slightly sassy accountability tutor and expert educator across all academic disciplines. 
Read the provided chat history from a group of students. Analyze it for two things:
1. Academic Misconceptions: Identify specific misunderstandings or gaps in knowledge regarding whatever subject they are studying (e.g., History, Math, Literature, Science). Automatically gauge their academic level based on their vocabulary and topics.
2. Procrastination Trends: Determine if the group is actually studying or getting distracted.
3. Ignore all bot commands and any off-topic banter that doesn't relate to their studies.

Output strictly in JSON format matching the schema. 
- If they are severely off-task, set 'action_required' to "lock_in" and write a strict, motivational 'summary_message' telling them to focus.
- If they have academic misconceptions, set 'action_required' to "explain". Write a supportive 'summary_message' highlighting their gaps and ask: "I’ve noticed some confusion regarding [Topic]. Would you like a deep-dive explanation?"
"""

HTML_GENERATOR_PROMPT = """
You are an expert educator and technical writer capable of teaching any subject at any level. The users have requested a deep-dive study guide to correct specific misconceptions identified in their recent chat.

Your task is to generate a comprehensive, visually stunning, standalone HTML study guide addressing these topics.

Strict Requirements:
1. Output ONLY valid, raw HTML. Do not wrap the output in markdown code blocks (NO ```html).
2. Adapt your tone, vocabulary, and depth of explanation to the provided 'Student Level' and 'Subject Area'. Use highly relatable analogies tailored to that age group.
3. Use a modern "Dark Mode" aesthetic. Embed Tailwind CSS via CDN (<script src="[https://cdn.tailwindcss.com](https://cdn.tailwindcss.com)"></script>).
4. Include a <style> block with a `@media print` query ensuring the document prints cleanly on physical paper (black text on white background).
5. Structure the content beautifully based on the subject (e.g., use blockquotes for Literature/History, well-styled formula boxes for Math/Physics, code blocks for CS).
6. Directly and gently correct the specific misconceptions they had. Include a "TL;DR Printable Notes" summary section at the bottom.
7. Add  print button at botom right corner that triggers the browser's print function for easy printing of the study guide.
8. use gradient of colors: 000000 nand #c89116
9. add footer: "generated by panikbot, saving grades one ping at a time"
10. IMAGES: You will be provided with a list of image URLs sourced from Wikipedia. ONLY embed an image if it is genuinely useful for understanding the concept (e.g. diagrams, graphs, charts, scientific illustrations, formula visualisations). Do NOT embed images that are:
    - Photos of people, buildings, or places
    - Logos, icons, or decorative images
    - Unrelated to the explanation
    If an image URL looks irrelevant based on its filename/context, skip it entirely. It is BETTER to have no images than to have irrelevant ones.
    When you do embed an image: Use <img> tags with Tailwind styling (rounded-lg, shadow-lg, mx-auto, max-w-md). Add descriptive alt text. Add a caption below with <p class="text-center text-sm text-gray-400 mt-1">. Place near the relevant explanation.
11. COMMUNITY KNOWLEDGE BASE: You may be provided with a "Community Knowledge" section containing explanations and tips written by real students who previously studied these topics and received 👍 upvotes from peers.
    - If community knowledge is provided, integrate the best insights naturally into your explanations.
    - Add a "✨ Community Spotlight" callout box (styled with a subtle gold/amber border and background) for particularly helpful community contributions.
    - Credit the original author using their @username in the callout, e.g. "💡 Tip from @Username:".
    - Only feature community tips that are accurate and genuinely helpful. Ignore or gently correct any community tips that contain misconceptions.
    - If no community knowledge is provided, simply skip this — do not mention it.
"""

QUIZ_GENERATOR_PROMPT = """
You are an expert educator creating a quiz to test students on material from their recent study session.
You will receive chat history and/or study guide content. Generate exactly 5 multiple-choice questions that:

1. Target the core concepts and common misconceptions from the provided material.
2. Have exactly 4 options each (A, B, C, D). Make distractors plausible but clearly wrong.
3. Adapt difficulty to the student level provided.
4. Include a short explanation for each correct answer.
5. Output strictly in JSON format matching the schema.
"""

# =====================================================================
# 3. IMAGE SEARCH (Wikimedia Commons — free, no API key)
# =====================================================================

# Words to strip from search queries for better image results
_FILLER_WORDS = {"and", "or", "the", "of", "in", "a", "an", "its", "their", "with", "for", "to", "on", "by", "is", "are", "was", "were", "that", "this", "from", "as", "at", "between", "relationships", "application", "applications", "understanding", "concepts", "concept", "basics"}


def _simplify_query(query: str) -> str:
    """Strip filler words and shorten query for better image search results."""
    words = [w for w in query.split() if w.lower().strip(",()") not in _FILLER_WORDS]
    # Keep max 3 meaningful keywords
    return " ".join(words[:3])


def search_images(query: str, count: int = 2) -> list[str]:
    """Search Wikipedia for images related to query. Returns list of image URLs.
    Uses Wikipedia's API to find article images (diagrams, charts, illustrations)
    which are far more relevant than random Commons search results."""
    simplified = _simplify_query(query)
    headers = {
        "User-Agent": "PanikBot/1.0 (https://github.com/panikbot; panikbot@example.com)",
    }

    # Step 1: Search Wikipedia for a relevant article
    search_url = "https://en.wikipedia.org/w/api.php"
    search_params = {
        "action": "query",
        "list": "search",
        "srsearch": simplified,
        "srlimit": "3",
        "format": "json",
    }
    try:
        resp = requests.get(search_url, params=search_params, headers=headers, timeout=10)
        resp.raise_for_status()
        search_results = resp.json().get("query", {}).get("search", [])
        if not search_results:
            print(f"  No Wikipedia articles found for '{simplified}'")
            return []
    except Exception as e:
        print(f"  Wikipedia search failed for '{simplified}': {e}")
        return []

    # Step 2: Get images from the top article(s)
    image_urls = []
    for article in search_results[:2]:
        title = article["title"]
        img_params = {
            "action": "query",
            "titles": title,
            "prop": "images",
            "imlimit": "20",
            "format": "json",
        }
        try:
            resp = requests.get(search_url, params=img_params, headers=headers, timeout=10)
            resp.raise_for_status()
            pages = resp.json().get("query", {}).get("pages", {})
            for page in pages.values():
                for img in page.get("images", []):
                    img_title = img.get("title", "")
                    # Filter: only keep SVGs/PNGs that look like diagrams, not icons or logos
                    lower = img_title.lower()
                    # Skip irrelevant images
                    if any(skip in lower for skip in ["icon", "logo", "flag", "commons-logo", "wiki", "edit", "button", "symbol", "medal", "award", "portrait", "photo", "folder", "ambox", "padlock", "question_book", "text-x"]):
                        continue
                    if not any(ext in lower for ext in [".svg", ".png", ".jpg", ".jpeg"]):
                        continue

                    # Step 3: Get the actual image URL
                    url_params = {
                        "action": "query",
                        "titles": img_title,
                        "prop": "imageinfo",
                        "iiprop": "url|mime",
                        "iiurlwidth": "800",
                        "format": "json",
                    }
                    try:
                        img_resp = requests.get(search_url, params=url_params, headers=headers, timeout=10)
                        img_resp.raise_for_status()
                        img_pages = img_resp.json().get("query", {}).get("pages", {})
                        for img_page in img_pages.values():
                            info = img_page.get("imageinfo", [{}])[0]
                            mime = info.get("mime", "")
                            if not mime.startswith("image/"):
                                continue
                            thumb = info.get("thumburl") or info.get("url")
                            if thumb:
                                image_urls.append(thumb)
                                if len(image_urls) >= count:
                                    return image_urls
                    except Exception:
                        continue
        except Exception:
            continue

    return image_urls


def search_images_for_topics(topics: list[str], per_topic: int = 2) -> dict[str, list[str]]:
    """Search for educational images for each topic. Returns {topic: [url, ...]}"""
    result = {}
    for topic in topics:
        urls = search_images(topic, count=per_topic)
        if urls:
            result[topic] = urls
            print(f"  🖼️ Found {len(urls)} images for '{topic}'")
        else:
            print(f"  ⚠️ No images found for '{topic}'")
    return result


# =====================================================================
# 4. CORE FUNCTIONS
# =====================================================================
def analyze_chat(chat_history: str) -> dict:
    """Takes the raw Discord chat string and returns a structured JSON analysis."""
    print("Analyzing chat history...")
    
    response = client.models.generate_content(
        model=MODEL_ID,
        contents=chat_history,
        config=types.GenerateContentConfig(
            system_instruction=ANALYZER_PROMPT,
            response_mime_type="application/json",
            response_schema=ChatAnalysis,
            temperature=0.2, 
        ),
    )
    
    return response.parsed.model_dump()


def generate_html_resource(chat_history: str, topics: list[str], student_level: str, subject_area: str, rag_context: str = "") -> str:
    """Generates the HTML study notes based on the chat history and metadata, saving it to responses/"""
    print(f"Generating HTML resource for {student_level} {subject_area} on topics: {topics}...")

    # Search for relevant images
    print("Searching for relevant images...")
    topic_images = search_images_for_topics(topics, per_topic=2)

    # Build image list for the prompt
    image_section = ""
    if topic_images:
        image_lines = []
        for topic, urls in topic_images.items():
            for url in urls:
                image_lines.append(f"  - Topic: {topic} | URL: {url}")
        image_section = "\n".join(image_lines)
    else:
        image_section = "No images available."

    # Build community knowledge section
    community_section = ""
    if rag_context.strip():
        community_section = f"""
    Community Knowledge (upvoted explanations from fellow students — integrate the best ones):
{rag_context}
"""
    else:
        community_section = "    Community Knowledge: None available yet."

    # Combine the context for the generator so it knows exactly how to pitch the lesson
    prompt_context = f"""
    Subject Area: {subject_area}
    Student Level: {student_level}
    Topics to Explain: {', '.join(topics)}
    
    Available Images (embed these throughout the guide near relevant sections):
{image_section}
    
{community_section}

    Original Chat History for Context (address their exact misunderstandings):
    {chat_history}
    """

    response = client.models.generate_content(
        model=MODEL_ID,
        contents=prompt_context,
        config=types.GenerateContentConfig(
            system_instruction=HTML_GENERATOR_PROMPT,
            temperature=0.7, 
        ),
    )

    # Clean up the response in case Gemini includes markdown backticks
    html_content = response.text.strip()
    if html_content.startswith("```html"):
        html_content = html_content[7:]
    if html_content.endswith("```"):
        html_content = html_content[:-3]

    # Save to file
    os.makedirs("responses", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_name = f"study_guide_{timestamp}.html"
    file_path = os.path.join("responses", base_name)
    
    with open(file_path, "w", encoding='utf-8') as f:
        f.write(html_content)
        
    print(f"✅ HTML File saved to {file_path}")
    return base_name


def generate_quiz(chat_history: str, study_guide_content: str = "", student_level: str = "Unknown", subject_area: str = "Unknown") -> dict:
    """Generate a 5-question multiple-choice quiz from chat history and/or study guide content."""
    print(f"Generating quiz for {student_level} {subject_area}...")

    prompt_context = f"""
    Subject Area: {subject_area}
    Student Level: {student_level}

    Chat History:
    {chat_history}

    Study Guide Content (if available):
    {study_guide_content if study_guide_content else "No study guide available."}
    """

    response = client.models.generate_content(
        model=MODEL_ID,
        contents=prompt_context,
        config=types.GenerateContentConfig(
            system_instruction=QUIZ_GENERATOR_PROMPT,
            response_mime_type="application/json",
            response_schema=QuizOutput,
            temperature=0.4,
        ),
    )

    return response.parsed.model_dump()


# =====================================================================
# Example Usage (You can delete this block when importing to your bot)
# =====================================================================
if __name__ == "__main__":
    # Define a dummy chat string to test (no file needed now!)
    dummy_chat = (
        "User1: Bro what even is a linked list, is it just an array with pointers?\n"
        "User2: I think so, but searching takes O(1) time right?\n"
        "User1: Yeah probably."
    )
    
    # Step 1: Analyze the raw string directly
    print("Testing Analysis...")
    result = analyze_chat(dummy_chat)
    
    print("\n--- API RESULT ---")
    print(json.dumps(result, indent=2))
    
    # Step 2: If the bot gets confirmation from Discord, generate HTML
    if result.get("action_required") == "explain":
        saved_file = generate_html_resource(
            chat_history=dummy_chat,  # Pass the string here, not a file path!
            topics=result["topics_to_explain"],
            student_level=result["student_level"],
            subject_area=result["subject_area"] 
        )
        print(f"\n🚀 SUCCESS! Your AWS sync script can now pick up: {saved_file}")
    else:
        print("\n🛑 Action required was 'lock_in'. No HTML generated. Telling them to focus!")